spring:
  datasource:
    url: jdbc:postgresql://bank_rest_db:5432/bank_rest_db
    username: sa
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml

swagger:
  enabled: true
  title: API Documentation
  version: 1.0.0
  base-package: com.example.bankcards.controller
  path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type: OFF
    org.hibernate.jdbc.bind: OFF

server:
  port: 8080